name: release
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Increment "major", "minor", "patch", or "pre*" version; or specify version'
        default: patch
        required: true
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          registry-url: https://registry.npmjs.org/
          cache: yarn
      - run: yarn
      - run: yarn test
      - run: yarn build
      - name: Release
        run: |
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git config user.name "${GITHUB_ACTOR}"
          npm run release -- -- "${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
